# -*- coding: utf-8 -*-
"""TASK_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXO-P-ouRThaqx_JBU3W0VvSJQCqOwoA
"""

import pandas as pd
import matplotlib.pyplot as plt

"""**1. LOAD AND CLEAN DATA**"""

df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/AAPL.xlsx")

"""***Remove extra spaces from column names***"""

df.columns = df.columns.str.strip()

"""***Price attributes***"""

cols = ["Open", "High", "Low", "Close", "Volume"]

"""***Convert columns to numeric***"""

for col in cols:
    df[col] = pd.to_numeric(df[col])

"""***Check missing values and duplicates***"""

print("Missing Values:")
print(df[cols].isnull().sum())
print("\nDuplicate Records:", df.duplicated().sum())

"""***Remove missing values and duplicates***"""

df = df.dropna(subset=cols)
df = df.drop_duplicates()
print("\nCleaned Data:")
print(df.head())

"""**2. DAILY PRICE DELTA**"""

df["Price_Delta"] = df["Close"] - df["Open"]

print("\nDaily Price Delta:")
print(df[["Open", "Close", "Price_Delta"]].head())

"""**3. DAILY PERCENTAGE RETURN**"""

df["Daily_Return"] = (
    (df["Close"] - df["Open"]) / df["Open"]
) * 100

print("\nDaily Percentage Return:")
print(df[["Open", "Close", "Daily_Return"]].head())

"""**4. TRADING VOLUME TREND**

***5-day moving average***
"""

df["Volume_MA"] = df["Volume"].rolling(5).mean()

print("\nTrading Volume Trend:")
print(df[["Volume", "Volume_MA"]].head())

"""***Visualization 1: Volume Trend***"""

df["Volume_MA"] = df["Volume"].rolling(5).mean()
plt.figure(figsize=(10, 5))

plt.plot(df["Volume"], label="Trading Volume")
plt.plot(df["Volume_MA"], label="5-Day Moving Average")

plt.title("Trading Volume Trend")
plt.xlabel("Trading Days")
plt.ylabel("Volume")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""**5. ANOMALOUS TRADING DAYS**"""

mean_volume = df["Volume"].mean()
std_volume = df["Volume"].std()

"""***Volume outside ±2 standard deviations***"""

df["Volume_Anomaly"] = (
    abs(df["Volume"] - mean_volume) > 2 * std_volume
)

anomalies = df[df["Volume_Anomaly"]]

print("\nAnomalous Trading Days:")
print(anomalies[["Volume"]])

"""***Visualization 2: Anomalous Days***"""

plt.figure(figsize=(10, 5))

plt.plot(df.index, df["Volume"], label="Trading Volume")

plt.scatter(
    anomalies.index,
    anomalies["Volume"],
    label="Anomalous Days"
)

plt.title("Anomalous Trading Days")
plt.xlabel("Trading Days")
plt.ylabel("Volume")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""**6. STOCK RETURN DISTRIBUTION**"""

mean_return = df["Daily_Return"].mean()
variance_return = df["Daily_Return"].var()
std_return = df["Daily_Return"].std()

print("\nStock Return Distribution")
print("--------------------------------")
print("Mean                 :", mean_return)
print("Variance             :", variance_return)
print("Standard Deviation   :", std_return)

"""***Visualization 3: Return Distribution***"""

plt.figure(figsize=(8, 5))

plt.hist(df["Daily_Return"], bins=30)

plt.title("Daily Return Distribution")
plt.xlabel("Daily Return (%)")
plt.ylabel("Frequency")
plt.grid(True)
plt.tight_layout()
plt.show()

"""**7. FINAL SUMMARY**"""

print("\n========== FINAL SUMMARY ==========")
print("Total Clean Records    :", len(df))
print("Average Daily Return   :", mean_return)
print("Return Variance        :", variance_return)
print("Return Std Deviation   :", std_return)
print("Average Trading Volume :", df["Volume"].mean())
print("Anomalous Days         :", len(anomalies))