# -*- coding: utf-8 -*-
"""TASK_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vF5_gReuu7WAy0Epr7pd0IX4a2SwCFO4
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**1. LOAD AND CLEAN DATA**"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/shopify_stock.csv")
df.columns = df.columns.str.strip()
cols = ["open", "high", "low", "close", "volume"]
for col in cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
df = df.dropna(subset=cols)
df = df.drop_duplicates()

"""***Convert Date if available***"""

if "Date" in df.columns:
    df["Date"] = pd.to_datetime(df["Date"])
    df = df.sort_values("Date")

"""**2. DAILY RETURNS**"""

df["Daily_Return"] = (
    (df["close"] - df["open"]) / df["open"]
) * 100

"""**3. OHLC PRICE AND VOLUME LINE PLOTS**"""

x = df["Date"] if "Date" in df.columns else df.index

plt.figure(figsize=(12, 6))

plt.plot(x, df["open"], label="Open")
plt.plot(x, df["high"], label="High")
plt.plot(x, df["low"], label="Low")
plt.plot(x, df["close"], label="Close")

plt.title("OHLC Prices Over Time")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


plt.figure(figsize=(12, 5))

plt.plot(x, df["volume"], label="Trading Volume")

plt.title("Trading Volume Over Time")
plt.xlabel("Date")
plt.ylabel("Volume")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""**4. 20-DAY AND 50-DAY MOVING AVERAGES**"""

df["MA_20"] = df["close"].rolling(20).mean()
df["MA_50"] = df["close"].rolling(50).mean()

plt.figure(figsize=(12, 6))

plt.plot(x, df["close"], label="Daily Close")
plt.plot(x, df["MA_20"], label="20-Day Moving Average")
plt.plot(x, df["MA_50"], label="50-Day Moving Average")

plt.title("Closing Price with Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""**5. DAILY RETURN HISTOGRAM AND KDE**"""

sns.histplot(
    df["Daily_Return"],
    bins=30,
    kde=True,
    stat="density"
)

plt.title("Daily Return Distribution")
plt.xlabel("Daily Return (%)")
plt.ylabel("Frequency")
plt.grid(True)
plt.tight_layout()
plt.show()

"""**6. RETURN STATISTICS**"""

mean_return = df["Daily_Return"].mean()
variance_return = df["Daily_Return"].var()
std_return = df["Daily_Return"].std()

high_volatility = df[
    abs(df["Daily_Return"]) > 2 * std_return
]

print("\n========== FINANCIAL SUMMARY REPORT ==========")

print("\nReturn Statistics")
print("--------------------------------")
print("Mean Return          :", round(mean_return, 4), "%")
print("Variance             :", round(variance_return, 4))
print("Standard Deviation   :", round(std_return, 4), "%")

print("\nPrice Statistics")
print("--------------------------------")
print("Highest Closing Price:", df["close"].max())
print("Lowest Closing Price :", df["close"].min())

print("\nTrading Volume")
print("--------------------------------")
print("Average Volume       :", round(df["volume"].mean(), 2))
print("Maximum Volume       :", df["volume"].max())

print("\nHigh-Volatility Days")
print("--------------------------------")
print("Number of Days       :", len(high_volatility))

if len(high_volatility) > 0:
    print("\nHigh-Volatility Records:")
    print(
        high_volatility[
            ["open", "close", "Daily_Return", "volume"]
        ]
    )

print("\n========== INTERPRETATION ==========")

if std_return < 2:
    print("Stock Stability: Relatively stable returns.")
else:
    print("Stock Stability: Higher variation in daily returns.")

print(
    "High-volatility periods are identified using "
    "daily returns beyond ±2 standard deviations."
)