# -*- coding: utf-8 -*-
"""TASK_7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYBl_s-OYZCFoXrNOnxz45mNN8WRQFlI
"""

import pandas as pd
import numpy as np

"""**1. LOAD DATASET**"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/StudentsPerformance.csv")

print("First 5 Records:")
print(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

"""**2. CLEAN CATEGORICAL FEATURES**"""

df.columns = df.columns.str.strip().str.title()
print("Column Names:")

for col in df.columns:
    print(col)


categorical_columns = [
    "Gender",
    "Race/Ethnicity",
    "Parental Level Of Education",
    "Lunch",
    "Test Preparation Course"
]

for col in categorical_columns:
    df[col] = df[col].fillna("Unknown").str.strip().str.title()

print("\nCleaned Categorical Features:")
print(df[categorical_columns].head())

"""**3. STATISTICAL MEASURES FOR SUBJECT SCORES**"""

subjects = [
    "Math Score",
    "Reading Score",
    "Writing Score"
]

statistics = df[subjects].agg(
    ["mean", "median", "std"]
).T

statistics["Q1"] = df[subjects].quantile(0.25)
statistics["Q3"] = df[subjects].quantile(0.75)

print("\nSubject Score Statistics:")
print(statistics)

"""**4. CALCULATE TOTAL MARKS**"""

df["Total Marks"] = (
    df["Math Score"] +
    df["Reading Score"] +
    df["Writing Score"]
)
print("\nTotal Marks:")
print(df["Total Marks"].head())

"""**5. CALCULATE PERCENTAGE PERFORMANCE**"""

df["Percentage"] = (df["Total Marks"] / 300) * 100


print("\nTotal Marks and Percentage:")
print(df[
    ["Math Score", "Reading Score",
     "Writing Score", "Total Marks", "Percentage"]
].head())

"""**6. DETECT PERFORMANCE OUTLIERS**"""

print("\nPerformance Outliers:")

for subject in subjects:

    Q1 = df[subject].quantile(0.25)
    Q3 = df[subject].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[
        (df[subject] < lower_limit) |
        (df[subject] > upper_limit)
    ]

    print("\n", subject)
    print(outliers[
        [subject, "Total Marks", "Percentage"]
    ])

"""**7. FINAL DATASET**"""

print("\nFinal Dataset:")
print(df.head())

print("\nFinal Shape:")
print(df.shape)