# -*- coding: utf-8 -*-
"""TASK-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xV3xYkGGpkEXlQ3tXkfTq-xcujhMfUS9

# **TASK 1: SUPERSTORE SALES DATA UNDERSTANDING, CLEANING & EXPLORATORY ANALYSIS**

###**STEP 1: IMPORT REQUIRED LIBRARIES**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### **STEP 2: LOAD THE SUPERSTORE DATASET**"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/samplesuperstore.csv")

"""### **STEP 3: DISPLAY THE FIRST FIVE ROWS OF THE DATASET**"""

df.head()

"""### **STEP 4: DISPLAY DATASET INFORMATION**"""

df.info()

"""### **STEP 5: DISPLAY DESCRIPTIVE STATISTICS**

"""

df.describe()

"""### **STEP 6: CONVERT ORDER DATE AND SHIP DATE INTO DATETIME FORMAT**"""

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

"""### **STEP 7: VERIFY THE UPDATED DATA TYPES**"""

df.info()

"""### **STEP 8: CALCULATE DELIVERY DAYS**"""

df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days

"""### **STEP 9: DISPLAY THE UPDATED DATASET**

"""

df.head()

"""### **STEP 10: DISPLAY UNIQUE VALUES IN THE CATEGORY COLUMN**"""

df['Category'].unique()

"""### **STEP 11: CHECK FOR MISSING VALUES**"""

df.isnull().sum()

"""### **STEP 12: CALCULATE TOTAL SALES BY CATEGORY**"""

category_sales = (df.groupby('Category')['Sales'].sum())
category_sales

"""### **STEP 13: VISUALIZE TOTAL SALES BY CATEGORY**"""

category_sales.plot( kind='bar',figsize=(8,5),color='#C3B1E1')
plt.title("Sales by Category")
plt.ylabel("Total Sales")
plt.show()

"""### **STEP 14: VISUALIZE THE DISTRIBUTION OF SALES**"""

plt.figure(figsize=(8,5))
sns.histplot(df['Sales'],bins=30,color='#C3B1E1')
plt.title("Sales Distribution")
plt.show()