# -*- coding: utf-8 -*-
"""TASK_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eNtGALni3r7D0L6AMspUco3jdGaENc-m
"""

import pandas as pd

"""**1. LOAD DATASET**"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/healthcare_dataset.csv")

print("First 5 Records:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Information:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

"""**2. CLEAN MISSING MEDICAL CODES**"""

df["Medical Condition"] = df["Medical Condition"].fillna("Unknown")

"""**3. STANDARDIZE DATE ATTRIBUTES**"""

df["Date of Admission"] = pd.to_datetime(
    df["Date of Admission"]
)

df["Discharge Date"] = pd.to_datetime(
    df["Discharge Date"]
)

"""**4. CATEGORIZE ADMISSIONS BY URGENCY**"""

df["Urgency"] = df["Admission Type"].apply(
    lambda x: x if x in ["Emergency", "Elective", "Urgent"]
    else "Unknown"
)

print("\nAdmission by Urgency:")
print(df["Urgency"].value_counts())

"""**5. CALCULATE HOSPITAL STAY**"""

df["Hospital Stay Days"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days

"""**6. BILLING AMOUNT ANALYSI**"""

print("\nBilling Amount Statistics:")
print(df["Billing Amount"].describe())

"""**7. HOSPITAL STAY ANALYSIS**"""

print("\nHospital Stay Statistics:")
print(df["Hospital Stay Days"].describe())

"""**8. DEMOGRAPHIC SEGMENTATION**"""

print("\nDemographics by Medical Condition:")

demographics = df.groupby("Medical Condition")["Age"].agg(
    ["count", "mean", "min", "max"]
)

print(demographics)

"""**9. FINAL CLEANED DATA**"""

print("\nFinal Dataset:")
print(df.head())

print("\nFinal Shape:")
print(df.shape)