# -*- coding: utf-8 -*-
"""TASK_8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkK69ym-q-wu4Wh20J8FToVrmMSahB_E
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**LOAD DATASET**"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Studentperformance_preprecessed.csv")
print(df.head())

"""**1. GROUPED BAR CHART**"""

avg = df.groupby(
    ['Parental Level Of Education', 'Lunch']
)[['Math Score', 'Reading Score', 'Writing Score']].mean()

avg.plot(kind='bar', figsize=(12, 6))

plt.title("AVERAGE TEST SCORES BY PARENTAL EDUCATION AND LUNCH TYPE")
plt.xlabel("PARENTAL EDUCATION AND LUNCH TYPE")
plt.ylabel("AVERAGE SCORE")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**2. BOX PLOT**"""

plt.figure(figsize=(10, 6))

sns.boxplot(
    data=df,
    x="Test Preparation Course",
    y="Math Score"
)

plt.title("MATH SCORE VARIANCE BY TEST PREPARATION")
plt.xlabel("TEST PREPARATION COURSE")
plt.ylabel("MATH SCORE")
plt.show()

"""**3. SCATTER PLOT - MATH VS READING**"""

plt.figure(figsize=(6, 5))

sns.scatterplot(
    data=df,
    x="Math Score",
    y="Reading Score"
)

plt.title("MATH VS READING SCORES")
plt.xlabel("MATH SCORE")
plt.ylabel("READING SCORE")
plt.show()

"""**4. SCATTER PLOT - MATH VS WRITING**"""

plt.figure(figsize=(6, 5))

sns.scatterplot(
    data=df,
    x="Math Score",
    y="Writing Score"
)

plt.title("MATH VS WRITING SCORES")
plt.xlabel("MATH SCORE")
plt.ylabel("WRITING SCORE")
plt.show()

"""**5. SCATTER PLOT - READING VS WRITING**"""

plt.figure(figsize=(6, 5))

sns.scatterplot(
    data=df,
    x="Reading Score",
    y="Writing Score"
)

plt.title("READING VS WRITING SCORES")
plt.xlabel("READING SCORE")
plt.ylabel("WRITING SCORE")
plt.show()

"""**6. CORRELATION HEATMAP**"""

corr = df[
    ["Math Score", "Reading Score", "Writing Score"]
].corr()

plt.figure(figsize=(7, 5))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("CORRELATION HEATMAP OF TEST SCORES")
plt.tight_layout()
plt.show()